package com.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.2
 * 2019-04-03T20:39:39.595+02:00
 * Generated source version: 3.0.2
 * 
 */
@WebServiceClient(name = "BibliothekServiceService", 
                  wsdlLocation = "http://localhost:8080/bibliothek/BibliothekService?wsdl",
                  targetNamespace = "http://com/") 
public class BibliothekServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://com/", "BibliothekServiceService");
    public final static QName BibliothekServicePort = new QName("http://com/", "BibliothekServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/bibliothek/BibliothekService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(BibliothekServiceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/bibliothek/BibliothekService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public BibliothekServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public BibliothekServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BibliothekServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public BibliothekServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public BibliothekServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public BibliothekServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns BibliothekService
     */
    @WebEndpoint(name = "BibliothekServicePort")
    public BibliothekService getBibliothekServicePort() {
        return super.getPort(BibliothekServicePort, BibliothekService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BibliothekService
     */
    @WebEndpoint(name = "BibliothekServicePort")
    public BibliothekService getBibliothekServicePort(WebServiceFeature... features) {
        return super.getPort(BibliothekServicePort, BibliothekService.class, features);
    }

}
