package com.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.2
 * 2019-04-28T11:47:17.295+02:00
 * Generated source version: 3.0.2
 * 
 */
@WebService(targetNamespace = "http://com/", name = "BibliothekService")
@XmlSeeAlso({ObjectFactory.class})
public interface BibliothekService {

    @WebMethod
    @Action(input = "http://com/BibliothekService/createOuvrageRequest", output = "http://com/BibliothekService/createOuvrageResponse")
    @RequestWrapper(localName = "createOuvrage", targetNamespace = "http://com/", className = "com.ws.CreateOuvrage")
    @ResponseWrapper(localName = "createOuvrageResponse", targetNamespace = "http://com/", className = "com.ws.CreateOuvrageResponse")
    @WebResult(name = "return", targetNamespace = "")
    public int createOuvrage(
        @WebParam(name = "arg0", targetNamespace = "")
        com.ws.OuvragePojo arg0
    );

    @WebMethod
    @Action(input = "http://com/BibliothekService/createLoanRequest", output = "http://com/BibliothekService/createLoanResponse")
    @RequestWrapper(localName = "createLoan", targetNamespace = "http://com/", className = "com.ws.CreateLoan")
    @ResponseWrapper(localName = "createLoanResponse", targetNamespace = "http://com/", className = "com.ws.CreateLoanResponse")
    @WebResult(name = "return", targetNamespace = "")
    public int createLoan(
        @WebParam(name = "arg0", targetNamespace = "")
        com.ws.PretPojo arg0
    );

    @WebMethod
    @Action(input = "http://com/BibliothekService/identificationRequest", output = "http://com/BibliothekService/identificationResponse")
    @RequestWrapper(localName = "identification", targetNamespace = "http://com/", className = "com.ws.Identification")
    @ResponseWrapper(localName = "identificationResponse", targetNamespace = "http://com/", className = "com.ws.IdentificationResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.ws.UtilisateurResponse identification(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebMethod
    @Action(input = "http://com/BibliothekService/allAuteursRequest", output = "http://com/BibliothekService/allAuteursResponse")
    @RequestWrapper(localName = "allAuteurs", targetNamespace = "http://com/", className = "com.ws.AllAuteurs")
    @ResponseWrapper(localName = "allAuteursResponse", targetNamespace = "http://com/", className = "com.ws.AllAuteursResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.ws.AuteurResponse allAuteurs();

    @WebMethod
    @Action(input = "http://com/BibliothekService/allOuvragesRequest", output = "http://com/BibliothekService/allOuvragesResponse")
    @RequestWrapper(localName = "allOuvrages", targetNamespace = "http://com/", className = "com.ws.AllOuvrages")
    @ResponseWrapper(localName = "allOuvragesResponse", targetNamespace = "http://com/", className = "com.ws.AllOuvragesResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.ws.OuvrageResponse allOuvrages();

    @WebMethod
    @Action(input = "http://com/BibliothekService/createAuteurRequest", output = "http://com/BibliothekService/createAuteurResponse")
    @RequestWrapper(localName = "createAuteur", targetNamespace = "http://com/", className = "com.ws.CreateAuteur")
    @ResponseWrapper(localName = "createAuteurResponse", targetNamespace = "http://com/", className = "com.ws.CreateAuteurResponse")
    @WebResult(name = "return", targetNamespace = "")
    public int createAuteur(
        @WebParam(name = "arg0", targetNamespace = "")
        com.ws.AuteurPojo arg0
    );

    @WebMethod
    @Action(input = "http://com/BibliothekService/getAuteurRequest", output = "http://com/BibliothekService/getAuteurResponse")
    @RequestWrapper(localName = "getAuteur", targetNamespace = "http://com/", className = "com.ws.GetAuteur")
    @ResponseWrapper(localName = "getAuteurResponse", targetNamespace = "http://com/", className = "com.ws.GetAuteurResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.ws.AuteurResponse getAuteur(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );

    @WebMethod
    @Action(input = "http://com/BibliothekService/getOuvrageRequest", output = "http://com/BibliothekService/getOuvrageResponse")
    @RequestWrapper(localName = "getOuvrage", targetNamespace = "http://com/", className = "com.ws.GetOuvrage")
    @ResponseWrapper(localName = "getOuvrageResponse", targetNamespace = "http://com/", className = "com.ws.GetOuvrageResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.ws.OuvrageResponse getOuvrage(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );

    @WebMethod
    @Action(input = "http://com/BibliothekService/loanReturnRequest", output = "http://com/BibliothekService/loanReturnResponse")
    @RequestWrapper(localName = "loanReturn", targetNamespace = "http://com/", className = "com.ws.LoanReturn")
    @ResponseWrapper(localName = "loanReturnResponse", targetNamespace = "http://com/", className = "com.ws.LoanReturnResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.ws.PretResponse loanReturn(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );

    @WebMethod
    @Action(input = "http://com/BibliothekService/updateAuteurRequest", output = "http://com/BibliothekService/updateAuteurResponse")
    @RequestWrapper(localName = "updateAuteur", targetNamespace = "http://com/", className = "com.ws.UpdateAuteur")
    @ResponseWrapper(localName = "updateAuteurResponse", targetNamespace = "http://com/", className = "com.ws.UpdateAuteurResponse")
    public void updateAuteur(
        @WebParam(name = "arg0", targetNamespace = "")
        com.ws.AuteurPojo arg0
    );

    @WebMethod
    @Action(input = "http://com/BibliothekService/deleteAuteurRequest", output = "http://com/BibliothekService/deleteAuteurResponse")
    @RequestWrapper(localName = "deleteAuteur", targetNamespace = "http://com/", className = "com.ws.DeleteAuteur")
    @ResponseWrapper(localName = "deleteAuteurResponse", targetNamespace = "http://com/", className = "com.ws.DeleteAuteurResponse")
    public void deleteAuteur(
        @WebParam(name = "arg0", targetNamespace = "")
        com.ws.AuteurPojo arg0
    );

    @WebMethod
    @Action(input = "http://com/BibliothekService/getUserRequest", output = "http://com/BibliothekService/getUserResponse")
    @RequestWrapper(localName = "getUser", targetNamespace = "http://com/", className = "com.ws.GetUser")
    @ResponseWrapper(localName = "getUserResponse", targetNamespace = "http://com/", className = "com.ws.GetUserResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.ws.UtilisateurResponse getUser(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );

    @WebMethod
    @Action(input = "http://com/BibliothekService/getLoanRequest", output = "http://com/BibliothekService/getLoanResponse")
    @RequestWrapper(localName = "getLoan", targetNamespace = "http://com/", className = "com.ws.GetLoan")
    @ResponseWrapper(localName = "getLoanResponse", targetNamespace = "http://com/", className = "com.ws.GetLoanResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.ws.PretResponse getLoan(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );

    @WebMethod
    @Action(input = "http://com/BibliothekService/allLoansRequest", output = "http://com/BibliothekService/allLoansResponse")
    @RequestWrapper(localName = "allLoans", targetNamespace = "http://com/", className = "com.ws.AllLoans")
    @ResponseWrapper(localName = "allLoansResponse", targetNamespace = "http://com/", className = "com.ws.AllLoansResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.ws.PretResponse allLoans();

    @WebMethod
    @Action(input = "http://com/BibliothekService/extendLoanRequest", output = "http://com/BibliothekService/extendLoanResponse")
    @RequestWrapper(localName = "extendLoan", targetNamespace = "http://com/", className = "com.ws.ExtendLoan")
    @ResponseWrapper(localName = "extendLoanResponse", targetNamespace = "http://com/", className = "com.ws.ExtendLoanResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.ws.PretResponse extendLoan(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );

    @WebMethod
    @Action(input = "http://com/BibliothekService/notRenderedLoansRequest", output = "http://com/BibliothekService/notRenderedLoansResponse")
    @RequestWrapper(localName = "notRenderedLoans", targetNamespace = "http://com/", className = "com.ws.NotRenderedLoans")
    @ResponseWrapper(localName = "notRenderedLoansResponse", targetNamespace = "http://com/", className = "com.ws.NotRenderedLoansResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.ws.PretResponse notRenderedLoans();

    @WebMethod
    @Action(input = "http://com/BibliothekService/deleteOuvrageRequest", output = "http://com/BibliothekService/deleteOuvrageResponse")
    @RequestWrapper(localName = "deleteOuvrage", targetNamespace = "http://com/", className = "com.ws.DeleteOuvrage")
    @ResponseWrapper(localName = "deleteOuvrageResponse", targetNamespace = "http://com/", className = "com.ws.DeleteOuvrageResponse")
    public void deleteOuvrage(
        @WebParam(name = "arg0", targetNamespace = "")
        com.ws.OuvragePojo arg0
    );
}
